### ISSUE TITLE
No carga el dominio test-mecpage.com

### ISSUE THREAD

**Issue by maxiyommi** [mecantronic/sintetica-page#4]
En el despliegue de la branch `react` en hostinger al dominio [test-mecpage.com](https://test-mecpage.com/) la web figura en blanco:
![image](https://github.com/mecantronic/sintetica-page/assets/24780670/3186977e-6823-43b0-92e8-3bff5d718f61)

Y la consola arroja el siguiente error:
![image](https://github.com/mecantronic/sintetica-page/assets/24780670/3c98b993-54cb-4cb5-8dd5-679dc1b8d7a7)

**Comment by pauortegariera** [comment]
issue viejo, resuleto
