### ISSUE TITLE
Achicar el Logo de de Sintética - Cambiar el botón de "contactanos" por color gris

### ISSUE THREAD

**Issue by pauortegariera** [mecantronic/sintetica-page#5]
En branch vercel:

- [x] Reducir el tamaño del logo (el robot). El logo está un poco grande con respecto al tamaño del resto de los componentes, sólo un poco. 
- [x] Cambiar el color del botón de "contactanos" porque al ponerle el componente de forma violeta, no se distinguwe bien.

Dejo la imagen de referencia:

<img width="1434" alt="image" src="https://github.com/mecantronic/sintetica-page/assets/82551914/2e1c9ca7-5e67-4387-b707-31efc81491b0">

**Comment by ortega-pablo** [comment]
Resuelvo Issue y agrego responsive para esta sección.

Referencias: 
![5](https://github.com/mecantronic/sintetica-page/assets/87724507/2350d194-1b66-4aa9-99d0-793327ed6b1d)
![2](https://github.com/mecantronic/sintetica-page/assets/87724507/f78dcd58-b061-4aaf-b71e-a008570fa6c2)
![3](https://github.com/mecantronic/sintetica-page/assets/87724507/4ac8ac0f-62cc-40a8-a5db-9aedc38f8064)
![4](https://github.com/mecantronic/sintetica-page/assets/87724507/e2490dd4-1d86-4024-a140-858bba33acad)
![1](https://github.com/mecantronic/sintetica-page/assets/87724507/2f6a2aef-5680-4a14-a848-0a749a0f62cb)

**Comment by pauortegariera** [comment]
Modificaciones correctas.
