### ISSUE TITLE
Igual color para todas las cards de la sección

### ISSUE THREAD

**Issue by pauortegariera** [mecantronic/sintetica-page#6]
Branch vercel:

- [x] Setear el mismo color para todas las cards, el más claro
- [x] El botón "integraciones" y todos los de ese tipo son muy chiquitos, cambiar tamaño, agrandar un poquito.
- [x] Probar si la tipografía de los botones queda mejor en imprenta y mayúscula.

Imagen de referencia de la sección:

<img width="1295" alt="image" src="https://github.com/mecantronic/sintetica-page/assets/82551914/7f08aac8-a3c6-41bd-9bd0-d6f0aed42c3f">

**Comment by ortega-pablo** [comment]
Resuelvo Issue y agrego responsive para esta sección.

Referencias:
![5](https://github.com/mecantronic/sintetica-page/assets/87724507/85475090-16fd-4e43-8ec5-eac72d335287)
![4](https://github.com/mecantronic/sintetica-page/assets/87724507/8d7ff53e-24d3-4c1b-afcb-2012a977e055)
![1](https://github.com/mecantronic/sintetica-page/assets/87724507/1936ed79-c090-4ff4-86c5-6dc76c2dfa4c)
![2](https://github.com/mecantronic/sintetica-page/assets/87724507/0409b76f-5fb4-40ae-86c4-e435728d9b39)
![3](https://github.com/mecantronic/sintetica-page/assets/87724507/fd53206c-6038-4dab-afb1-c74cd1f06d11)

**Comment by pauortegariera** [comment]
Perfecto, todo implementado.
