### ISSUE TITLE
Padding de copys, títulos e imagen

### ISSUE THREAD

**Issue by pauortegariera** [mecantronic/sintetica-page#7]
En branch vercel:

- [x] Separar el texto de la imagen de los globos de conversaciones.
- [x] Achicar el ancho del texto de presentación del laboratorio. Se sale de los márgenes de las cards de arriba.
- [x] Probar cómo quedan los títulos en la tipografía que es imprenta y mayúscula. Evaluar y decidir cuál dejamos.
- [ ] 

Imagen de referencia:

<img width="1406" alt="image" src="https://github.com/mecantronic/sintetica-page/assets/82551914/602031f4-e7a0-4376-85a8-0c75bfebd9ec">

**Comment by ortega-pablo** [comment]
Resuelvo Issue y agrego responsive para esta sección.

Referencias:
![2](https://github.com/mecantronic/sintetica-page/assets/87724507/26516fef-35ad-436a-8de2-59aedf0cb190)
![1](https://github.com/mecantronic/sintetica-page/assets/87724507/957417a5-0835-4017-8c81-2dc22cc88a4d)

**Comment by pauortegariera** [comment]
Modificaciones correctas.
